# Generated by Django 5.2.4 on 2025-09-04 03:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_userloginlog_channel_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEmailAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated time"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("host", models.CharField(max_length=255, verbose_name="Host")),
                ("port", models.PositiveIntegerField(verbose_name="Port")),
                (
                    "protocol",
                    models.CharField(
                        choices=[("IMAP", "IMAP"), ("POP3", "POP3"), ("SMTP", "SMTP")],
                        max_length=10,
                        verbose_name="Protocol",
                    ),
                ),
                ("username", models.CharField(max_length=255, verbose_name="Username")),
                (
                    "_password",
                    models.CharField(
                        db_column="password", max_length=255, verbose_name="Password"
                    ),
                ),
                ("use_ssl", models.BooleanField(default=True, verbose_name="Use SSL")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User email account",
                "verbose_name_plural": "User email account",
                "ordering": ("-created_time",),
            },
        ),
    ]
